<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-3PMDTNC" failures="0" tests="9" name="TestNg.EcommerceTestGropsExample" time="0.035" errors="1" timestamp="2025-02-12T16:12:00 IST" skipped="3">
  <testcase classname="TestNg.EcommerceTestGropsExample" name="testAddToCart" time="0.014"/>
  <system-out/>
  <testcase classname="TestNg.EcommerceTestGropsExample" name="testUserLogin" time="0.005">
    <skipped/>
  </testcase> <!-- testUserLogin -->
  <system-out/>
  <testcase classname="TestNg.EcommerceTestGropsExample" name="testLogout" time="0.002"/>
  <system-out/>
  <testcase classname="TestNg.EcommerceTestGropsExample" name="testUserLogin" time="0.001">
    <skipped/>
  </testcase> <!-- testUserLogin -->
  <system-out/>
  <testcase classname="TestNg.EcommerceTestGropsExample" name="testInvalidLogin" time="0.004"/>
  <system-out/>
  <testcase classname="TestNg.EcommerceTestGropsExample" name="testSearchProduct" time="0.005"/>
  <system-out/>
  <testcase classname="TestNg.EcommerceTestGropsExample" name="testCheckout" time="0.002"/>
  <system-out/>
  <testcase classname="TestNg.EcommerceTestGropsExample" name="testUserLogin" time="0.001">
    <error message="
Expected exception of type class java.lang.ArithmeticException but got java.lang.AssertionError: try these many attempts expected [true] but found [false]" type="org.testng.TestException">
      <![CDATA[org.testng.TestException: 
Expected exception of type class java.lang.ArithmeticException but got java.lang.AssertionError: try these many attempts expected [true] but found [false]
at org.testng.internal.ExpectedExceptionsHolder.wrongException(ExpectedExceptionsHolder.java:68)
at org.testng.internal.TestInvoker.considerExceptions(TestInvoker.java:739)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:634)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
Caused by: java.lang.AssertionError: try these many attempts expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at TestNg.EcommerceTestGropsExample.testUserLogin(EcommerceTestGropsExample.java:12)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
... 22 more
]]>
    </error>
  </testcase> <!-- testUserLogin -->
  <system-out/>
  <testcase classname="TestNg.EcommerceTestGropsExample" name="testUserLogin" time="0.001">
    <skipped/>
  </testcase> <!-- testUserLogin -->
  <system-out/>
</testsuite> <!-- TestNg.EcommerceTestGropsExample -->
